### ISSUE TITLE
paper/print for PointVS ?

### ISSUE THREAD

**Issue by linminhtoo** [jscant/PointVS#6]
hello Jack,

I chanced across your work on my github feed. I'm interested to learn more about PointVS, but I didn't find a link to a paper or preprint in your README specifically about the highlights of PointVS. Are you still in the midst of writing one?

Best,
Min Htoo

**Comment by jscant** [comment]
Hi Min,

The draft is almost done, and will be submitted in the next ~month or so - I will post here when it is posted to ChemRxiv.

Cheers,
Jack

**Comment by linminhtoo** [comment]
Fantastic, thanks! Good luck with the final push!

**Comment by jscant** [comment]
Preprint finally up at https://doi.org/10.1101/2022.10.28.511712
.
